### ISSUE TITLE
Implement SELECT

### ISSUE THREAD

**Issue by Lotes** [langium/langium-sql#3]
## `SELECT` arguments

* [ ] all-star column `*`
* [ ] all-table columns `t.*`
* See also expressions

## `FROM` arguments

* [ ] table
* [ ] sub query
* [ ] joins

## `WHERE` conditions

* See also expressions

## `GROUP BY` clause

* TODO

## `ORDER BY` clause

* TODO

## `HAVING` clause

* TODO

## `LIMIT` clause

* TODO

## Expressions

* [ ] #4
* [ ] #5
* [ ] #6
* [ ] #7
* [ ] LIKE operator
* [ ] SIMILAR TO operator
* [ ] IS (NOT) operator
* [ ] sub query
* [ ] string concatenation operator
* [ ] SUBSTRING(str FROM from FOR length)
* [ ] boolean operators
* [ ] arithmetic operators
* [ ] relational operators

**Comment by Lotes** [comment]
Too broad issue. Closing.
